[package]
name = "kangaji"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
env_logger = "0.11.3"
kvm-bindings = "0.8"
kvm-ioctls = "0.17"
libc = "0.2"
log = "0.4.21"
rand_chacha = "0.3.1"
