[package]
name = "kangaji"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
env_logger = "0.11.3"
kvm-bindings = "0.8"
kvm-ioctls = "0.17"
libafl = "0.12.0"
libafl_bolts = "0.12.0"
libc = "0.2"
log = "0.4.21"
rand = "0.8.5"
rand_core = "0.6.4"
vmm-sys-util = "0.12.1"
