[tasks.build]
command = "cargo"
args = [
    "build",
    "--release"
]

[tasks.run]
command = "cargo"
args = [
    "run",
    "--release",
    "--",
    "${@}"
]

[tasks.info]
env = { "RUST_LOG" = "info" }
run_task = "run"

[tasks.debug]
env = { "RUST_LOG" = "debug" }
run_task = "run"

[tasks.clean]
clear = true
script_runner = "@shell"
script = '''
rm -rf ./corpus
rm -rf ./solutions
cargo clean
'''